### ISSUE TITLE
多屏幕下不能正常运行

### ISSUE THREAD

**Issue by TOL0VE** [RigoLigoRLC/BugcheckScreensaver8#1]

**Comment by RigoLigoRLC** [comment]
现象和预期分别是什么样？手动触发一下蓝屏看看

**Comment by TOL0VE** [comment]
![微信图片_20231130121751](https://github.com/RigoLigoRLC/BugcheckScreensaver8/assets/38149298/3ebcfdc0-ca64-4a10-9a61-048142ecb368)

**Comment by TOL0VE** [comment]
![微信图片_20231130122159](https://github.com/RigoLigoRLC/BugcheckScreensaver8/assets/38149298/af812747-e5d8-4872-965f-8d6d357005c1)
手动蓝屏效果

**Comment by RigoLigoRLC** [comment]
后续我再凑个显示器试试吧，应该是要paint到主显示器的位置，至于屏保启动时窗口占据显示器的方式需要再查查

TOL0VE ***@***.***> 于 2023年11月30日周四 下午12:22写道：
